# Action to create a release apk when a tag is pushed to master branch.

name: Release
on:
  # Triggers the workflow on push events to the specified branch
  push:
#    branches: [ master ]
    tags:
      - 'v*'


jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true


#  publish:
#    name: Publish apk
#    runs-on: ubuntu-latest
#    needs: release
#
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#
#      - name: set up gradle properties
#        env:
#          HoverUsername: ${{ secrets.HOVER_USERNAME }}
#          HoverPassword: ${{ secrets.HOVER_PASSWORD }}
#          shell: bash
#          run: |
#            mkdir ~/.gradle
#            echo "GRADLE_USER_HOME=$HOME/.gradle" >> $GITHUB_ENV
#            echo "HoverUsername=$HoverUsername" >> ~/.gradle/gradle.properties
#            echo "HoverPassword=$HoverPassword" >> ~/.gradle/gradle.properties
#
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
